parameters:
- name: serviceConnection
  type: string
  default: ''
- name: dockerUsername
  type: string
  default: ''
- name: dockertag
  type: string
  default: ''
- name: tag 
  type: string
  default: ''
- name: services
  type: object
  default: []

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: Login
    containerRegistry: ${{ parameters.serviceConnection }}

- ${{ each svc in parameters.services }}:
  - task: Docker@2
    displayName: 'Push Docker ${{ svc.containerImage }}:${{ parameters.dockertag }}'
    inputs:
      containerRegistry: ${{ parameters.serviceConnection }}
      repository: ${{ parameters.dockerUsername }}/${{ svc.containerImage }}
      tags: |
        ${{ parameters.dockertag }}
        ${{ parameters.tag }}
      command: 'buildAndPush'
      Dockerfile: '$(System.DefaultWorkingDirectory)/${{ svc.artifactName }}/${{ svc.dockerFile }}'
      buildContext: '**'

