parameters:
- name: serviceConnection
  type: string
  default: ''
- name: tags 
  type: string
  default: ''
- name: dockerComposeFile
  type: string
  default: '**/docker-compose.yml'
- name: includeLatestTags
  type: boolean
  default: true

steps:
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: Login
    containerRegistry: ${{ parameters.serviceConnection }}

- task: NuGetAuthenticate@1 
  displayName: 'Authenticate to NuGet'

- task: DockerCompose@1
  displayName: Build Docker Compose
  inputs:
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: ${{ parameters.serviceConnection }}
    dockerComposeFile: ${{ parameters.dockerComposeFile }}
    projectName: 
    action: 'Build services'
    additionalImageTags:  ${{ parameters.tags }}
    includeLatestTag: ${{ parameters.includeLatestTag }}
    arguments: '--build-arg FEED_ACCESSTOKEN=$(VSS_NUGET_ACCESSTOKEN)'

- task: DockerCompose@1
  displayName: Push Docker Compose
  inputs:
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: ${{ parameters.serviceConnection }}
    dockerComposeFile: ${{ parameters.dockerComposeFile }}
    projectName: 
    action: 'Push services'
    additionalImageTags:  ${{ parameters.tags }}
    includeLatestTag: ${{ parameters.includeLatestTag }}