parameters:
- name: targetPath
  type: string
  default: ''
- name: artifactName
  type: string
  default: ''

steps:
- task: PublishPipelineArtifact@1
  displayName: 'Publish ${{ parameters.artifactName }} Artifact to Pipeline'
  inputs:
    targetPath: ${{ parameters.targetPath }}
    artifact: ${{ parameters.artifactName }}
    publishLocation: 'pipeline'