parameters:
- name: dotNetSdk
  type: string
  default: ''

steps:
  # workaround for bug https://github.com/microsoft/azure-pipelines-tasks/pull/19415
  # - task: PowerShell@2
  #   displayName: 'UseDotNet@2 fix'
  #   inputs:
  #     targetType: inline
  #     script: |
  #       Set-Content -Path 'C:\Program Files\dotnet\sdk\7.0.405.complete' -Value 'dummy'

  - task: UseDotNet@2
    displayName: 'Use .NET Core SDK Version ${{ parameters.dotNetSdk }}'
    inputs:
      version: ${{ parameters.dotNetSdk }}
      performMultiLevelLookup: true
      # installationPath: 'C:\Program Files\dotnet' 
