parameters:
- name: terraformWorkingDirectory
  type: string
  default: ''
- name: azureSubscription
  type: string
  default: ''

steps:
- task: TerraformTaskV4@4
  name: terraformApply
  displayName: 'Terraform Apply'
  condition: eq(variables['terraformPlan.changesPresent'], 'true')
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: '-auto-approve terraform.tfplan'
    environmentServiceNameAzureRM: '${{ parameters.azureSubscription }}'
    workingDirectory: ${{ parameters.terraformWorkingDirectory }}

