parameters:
- name: terraformWorkingDirectory
  type: string
  default: ''
- name: terraformState
  type: string
  default: ''

steps:
- task: DownloadPipelineArtifact@2
  displayName: 'Download Terraform state'
  inputs:
    buildType: 'current'
    artifactName: '${{ parameters.terraformState }}'
    targetPath: '${{ parameters.terraformWorkingDirectory }}'
  continueOnError: true