parameters:
- name: terraformWorkingDirectory
  type: string
  default: ''
- name: azureSubscription
  type: string
  default: ''
- name: fmtOptions
  type: string
  default: '--check --diff'

steps:
- template: ../tasks/terraform-format.yml
  parameters:
    terraformWorkingDirectory: ${{ parameters.terraformWorkingDirectory }}
    fmtOptions: ${{ parameters.fmtOptions }}

- task: TerraformTaskV4@4
  name: terraformValidate
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    environmentServiceNameAzureRM: '${{ parameters.azureSubscription }}'
    workingDirectory: ${{ parameters.terraformWorkingDirectory }}